stages:
  - build
  - push
build:
  stage: build
  script:
    - docker build -t docker.io/dpizarro/gitlab-ci-android:latest .
push:
  stage: push
  script:
    - docker push docker.io/dpizarro/gitlab-ci-android:latest

