stages:
  - build
  - push
build:
  stage: build
  script:
    - docker build -t dpizarro/gitlab-ci-android:latest .
push:
  stage: push
  script:
    - docker push dpizarro/gitlab-ci-android:latest

